### PR TITLE
fix: span is missing in multi client request

### PR DESCRIPTION
**Pull request by gxcsoccer**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

一个 controller 下并行请求多个服务，会被覆盖，理想应该是下面样子，实际上只有一个 child span

image

### CODE REVIEW

**Review by fengmk2 — APPROVED** [review]

**Comment by fengmk2** [comment]
@gxcsoccer 你来发包。

**Review by popomore — COMMENTED** [review]
LGTM

**Comment by gxcsoccer** [comment]
@fengmk2 我没权限

**Comment by popomore** [comment]
+ egg-opentracing@1.1.1

**Comment by popomore** [comment]
npm owner ls           
dead-horse <dead_horse@qq.com>
gxcsoccer <gxcsoccer@gmail.com>
fengmk2 <fengmk2@gmail.com>
popomore <sakura9515@gmail.com>

**Pull request merged**
